#!/usr/bin/env python

# save several seismo signals 
# Specialized script used to visualize seismic section.

# create on Tue Jul 17 14:57:36 UTC 2018
# Creator: Jiaze He 

# import argparse

from obspy import read
import matplotlib.pyplot as plt

from seisflows.tools.graphics import plot_vector, plot_section

import numpy as np

# for file finding
import glob

OUTPUT_FILES_path = "OUTPUT_FILES"

signal_type_list = glob.glob(OUTPUT_FILES_path + '/' + "U*.txt")

for f in signal_type_list:
    print(f)
    fhead=(f[len(OUTPUT_FILES_path)+1:len(OUTPUT_FILES_path)+3])

    data_load = np.loadtxt(f)
    
    mat_rec_plot = np.array([1, 3, 225]) 
    num_rec = len(mat_rec_plot)
    
    time_function_type = 8
    
    if time_function_type == 8: 
        usct_load = np.loadtxt("DATA/usct_source_funcv12")
        t = usct_load[:,0]      
    
    for i in range(num_rec):
        col_num = mat_rec_plot[i] 
        titlename = fhead + ' receiver: %d ' % (col_num) 
        plt.subplot(num_rec, 1, i+1)
        plt.plot(t, data_load[:,col_num], '-')
        plt.title(titlename)
    u_receives_signals_fn = OUTPUT_FILES_path + '/' + 'receives_signals_' + fhead 
    plt.savefig(u_receives_signals_fn, format='eps', dpi=1000)
    #plt.savefig('OUTPUT_FILES/u_receives_signals.png', format='png')
    #plt.show()     



     
